import type { Alert, Incident, NewsPost, Offer } from './types';

import newsCover1 from '@/assets/primary-school/random/random1.jpg';
import newsCover2 from '@/assets/primary-school/random/random2.jpg';
import newsCover3 from '@/assets/primary-school/random/random3.jpg';
import newsCover4 from '@/assets/secondary-school/school/random1.jpg';

const now = new Date().toISOString();

export const mockNewsPosts: NewsPost[] = [
    {
        id: '1',
        title: 'Martin House Opens 2026 Enrolment Window',
        slug: '2026-enrolment-window-opens',
        content: '<p>Martin House is pleased to announce that applications for the 2026 academic year are now open. Families are invited to visit our campus, meet our leadership team, and discover how we nurture academic excellence alongside character development.</p><p>Our admissions team is available to guide you through the application process and answer any questions about programmes, boarding, and extracurricular opportunities.</p>',
        excerpt: 'Applications for the 2026 academic year are now open at Martin House.',
        category: 'Admissions',
        author: 'Martin House Admissions',
        cover_image: newsCover1,
        meta_description: 'Applications for the 2026 academic year are now open at Martin House.',
        is_published: true,
        scheduled_at: null,
        published_at: now,
        created_at: now,
        updated_at: now,
        created_by: null,
        views: 0,
    },
    {
        id: '2',
        title: 'Students Excel at National Science Fair',
        slug: 'national-science-fair-success',
        content: '<p>Congratulations to our Form Four students who represented Martin House at the National Science Fair, earning top honours in the environmental sciences category.</p><p>Their project on sustainable water management showcased the innovation and research skills we cultivate across our STEM programmes.</p>',
        excerpt: 'Martin House students earned top honours at the National Science Fair.',
        category: 'Achievements',
        author: 'Martin House Communications',
        cover_image: newsCover2,
        meta_description: 'Martin House students earned top honours at the National Science Fair.',
        is_published: true,
        scheduled_at: null,
        published_at: now,
        created_at: now,
        updated_at: now,
        created_by: null,
        views: 0,
    },
    {
        id: '3',
        title: 'Community Outreach Day Brings Students and Neighbours Together',
        slug: 'community-outreach-day',
        content: '<p>Our annual Community Outreach Day brought together students, staff, and local partners for a day of service and learning beyond the classroom.</p><p>From literacy programmes to environmental clean-ups, Martin House students demonstrated leadership, empathy, and a commitment to making a positive impact.</p>',
        excerpt: 'Students and staff joined local partners for a day of community service.',
        category: 'Community',
        author: 'Martin House Communications',
        cover_image: newsCover3,
        meta_description: 'Students and staff joined local partners for a day of community service.',
        is_published: true,
        scheduled_at: null,
        published_at: now,
        created_at: now,
        updated_at: now,
        created_by: null,
        views: 0,
    },
    {
        id: '4',
        title: 'Core Values Week Highlights Character Education',
        slug: 'core-values-week',
        content: '<p>Core Values Week celebrated the principles that guide life at Martin House: integrity, respect, excellence, and service.</p><p>Through assemblies, workshops, and peer-led discussions, students reflected on what it means to lead with purpose in school and in the wider community.</p>',
        excerpt: 'Core Values Week celebrated integrity, respect, excellence, and service.',
        category: 'School Life',
        author: 'Martin House Editor',
        cover_image: newsCover4,
        meta_description: 'Core Values Week celebrated integrity, respect, excellence, and service.',
        is_published: true,
        scheduled_at: null,
        published_at: now,
        created_at: now,
        updated_at: now,
        created_by: null,
        views: 0,
    },
];

export const mockAlerts: Alert[] = [
    {
        id: '1',
        title: 'Term Two Reports Available on Parent Portal',
        description: '<p>Term Two academic reports are now available on the parent portal. Please log in to review your child\'s progress and teacher comments.</p>',
        severity: 'medium',
        cover_image: newsCover2,
        is_active: true,
        is_published: true,
        scheduled_at: null,
        published_at: now,
        expires_at: null,
        created_at: now,
        updated_at: now,
        created_by: null,
    },
    {
        id: '2',
        title: 'School Closed for Public Holiday — Monday',
        description: '<p>Martin House will be closed on Monday for the public holiday. Classes resume Tuesday at the usual time.</p>',
        severity: 'high',
        cover_image: null,
        is_active: true,
        is_published: true,
        scheduled_at: null,
        published_at: now,
        expires_at: null,
        created_at: now,
        updated_at: now,
        created_by: null,
    },
];

export const mockIncidents: Incident[] = [
    {
        id: '1',
        title: 'Annual Sports Day',
        description: '<p>Join us for our Annual Sports Day featuring athletics, team games, and house competitions. All parents and guardians are welcome.</p>',
        category: 'Sports',
        severity: 'low',
        status: 'in_progress',
        reported_by: null,
        location: 'Main Sports Grounds',
        is_published: true,
        scheduled_at: null,
        published_at: now,
        resolved_at: null,
        created_at: now,
        updated_at: now,
        created_by: null,
    },
    {
        id: '2',
        title: 'Music & Arts Showcase Evening',
        description: '<p>Our Music & Arts Showcase Evening celebrates student talent across choir, orchestra, drama, and visual arts. Tickets available at reception.</p>',
        category: 'Arts',
        severity: 'low',
        status: 'pending',
        reported_by: null,
        location: 'School Auditorium',
        is_published: true,
        scheduled_at: null,
        published_at: now,
        resolved_at: null,
        created_at: now,
        updated_at: now,
        created_by: null,
    },
];

export const mockOffers: Offer[] = [
    {
        id: '1',
        title: 'STEM Enrichment Programme',
        description: '<p>An after-school STEM enrichment programme for Forms One to Three, focusing on robotics, coding, and applied mathematics.</p>',
        percentage_off: 0,
        cover_image: newsCover4,
        is_active: true,
        is_published: true,
        scheduled_at: null,
        published_at: now,
        expires_at: null,
        created_at: now,
        updated_at: now,
        created_by: null,
    },
    {
        id: '2',
        title: 'Leadership & Public Speaking Club',
        description: '<p>Develop confidence and communication skills through our Leadership & Public Speaking Club, open to all senior students.</p>',
        percentage_off: 0,
        cover_image: newsCover3,
        is_active: true,
        is_published: true,
        scheduled_at: null,
        published_at: now,
        expires_at: null,
        created_at: now,
        updated_at: now,
        created_by: null,
    },
];
